# Generated by Django 3.0 on 2019-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('income', models.FloatField()),
            ],
        ),
    ]
