# Generated by Django 3.0 on 2019-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.CharField(max_length=50),
        ),
    ]
