# Generated by Django 3.0 on 2019-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_auto_20191215_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_by_month',
            field=models.CharField(default=(100, 200, 300), max_length=200),
            preserve_default=False,
        ),
    ]
