# Generated by Django 3.0 on 2019-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_income_income_by_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_last_month',
            field=models.FloatField(default=4000),
            preserve_default=False,
        ),
    ]
