# Generated by Django 3.0 on 2019-12-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_income_income_last_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_difference',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
